# Pandas pratice

In [3]:
import pandas as pd 

df = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6],'c':[7,8,9]})
print(df)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9


In [4]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [5]:
print(df.columns)

Index(['a', 'b', 'c'], dtype='object')


In [6]:
print(df.values)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
print(df.abs)

<bound method NDFrame.abs of    a  b  c
0  1  4  7
1  2  5  8
2  3  6  9>


In [8]:
print(df.attrs)

{}


In [9]:
print(df.empty)

False


In [10]:
print(pd.DataFrame.abs(-1))

1


In [11]:
col = df['a']
print(col)

0    1
1    2
2    3
Name: a, dtype: int64


In [12]:
col = df.a
print(col)

0    1
1    2
2    3
Name: a, dtype: int64


In [13]:

df1=pd.DataFrame({'key':['a','b','c'],'value':[1,2,3]})  
print(df1)
print('---------------------')
df2=pd.DataFrame({'key':['d','e','f'],'value':[4,5,6]}) 
print(df2)
df3 = pd.concat([df1, df2])

  key  value
0   a      1
1   b      2
2   c      3
---------------------
  key  value
0   d      4
1   e      5
2   f      6


## Getting Started with real pandas

In [14]:
import pandas as pd

In [15]:
from pandas import Series, DataFrame

In [16]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [17]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [18]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
# can use the specific index to corrsponding data point
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c']) 

In [20]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [21]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [22]:
obj2['a']

-5

In [23]:
obj2['d'] = 6

In [24]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [25]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [26]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [27]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [28]:
'b' in obj2

True

In [29]:
'e' in obj2

False

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
# Passing a dict to pandas.Series
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [31]:
states = ['California', 'Ohio','Oregon', 'Texas']

In [32]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [39]:
obj4.name = 'population'
obj4.index.name = 'state'

In [40]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [41]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [42]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [43]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [44]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year':[2000, 2001, 2002, 2001, 2002, 2003], 'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [45]:
# Will get the result of dataframe having three dict as columns with align index by default
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [47]:
pd.DataFrame(data, columns= ['year', 'state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [55]:
frame2['debt'] = np.arange(6.)

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [57]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two','four','five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [61]:
del frame2['eastern']

In [62]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [63]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} 

In [64]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [65]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [66]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [67]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [68]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [69]:
frame3.index.name ='year';
frame3.columns.name = 'state'

In [70]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [71]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [72]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Ojects

In [73]:
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

index = obj.index

index

Index(['a', 'b', 'c'], dtype='object')

In [74]:
index[1:]

Index(['b', 'c'], dtype='object')

In [75]:
obj

a    0
b    1
c    2
dtype: int64

In [76]:
index[1] = 'd'
# Experimented a TypeError

TypeError: Index does not support mutable operations

In [77]:
labels = pd.Index(np.arange(3))

In [78]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [80]:
obj2 = pd.Series([1.5, -2.5, 0], index =labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [81]:
obj2.index is labels

True

In [82]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [84]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [85]:
'Ohio' in frame3.columns

True

In [86]:
2003 in frame3.index

False

In [87]:
dup_lables = pd.Index(['foo','foo','bar','bar'])

In [88]:
dup_lables

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [89]:
dup_lables.unique()

Index(['foo', 'bar'], dtype='object')

## Reindexing

In [91]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [92]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [94]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [97]:
obj3 = pd.Series(['blue', 'purple','yellow'], index = [0, 2, 4])

In [98]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [99]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [77]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index = ['a', 'c','d'], columns=['Ohio','Texas','California'])

In [78]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [79]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [84]:
states = ['Texas', 'California']
frame.reindex(columns = states)

Texas  California
a      1           2
c      4           5
d      7           8

In [87]:
frame.loc[['a', 'c', 'd'], states]

Texas  California
a      1           2
c      4           5
d      7           8

## Dropping Entries from an Axis

In [109]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])

In [110]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [111]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [113]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one', 'two', 'three', 'four'])

In [114]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data.drop(labels= ['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [117]:
data.drop(['two','four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [118]:
obj.drop('c',inplace= False)

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

In [119]:
obj = pd.Series(np.arange(4.), index =['a','b','c','d'])

In [120]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [121]:
obj['b']

1.0

In [122]:
obj[1]

1.0

In [123]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [124]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [125]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [126]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [127]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [128]:
obj['b':'c'] = 5

In [129]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [130]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns = ['one','two','three','four'])

In [131]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [142]:
data.index[1]

'Colorado'

In [143]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [144]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [145]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
data > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [147]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [148]:
data.loc['Colorado',['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [149]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [150]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [151]:
data.iloc[[1,2], [3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [153]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [154]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes

In [155]:
ser = pd.Series(np.arange(3.))

In [156]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [157]:
ser[-1]

KeyError: -1

In [158]:
ser2 = pd.Series(np.arange(3.), index = ['a','b','c'])

In [159]:
ser2[-1]

2.0

In [160]:
ser[:1]

0    0.0
dtype: float64

In [161]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

## Arutgnetic and Data Alignment      

In [162]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],             index=['a', 'c', 'e', 'f', 'g']) 
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [163]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [164]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado']) 

In [165]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon']) 

In [166]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [167]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [168]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [169]:
df1 = pd.DataFrame({'A': [1, 2]})
df1

A
0  1
1  2

In [171]:
df2 = pd.DataFrame({'B': [3, 4]})
df2

B
0  3
1  4

In [172]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

## Arithmetic methods with fill values

In [173]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

In [174]:
df2.loc[1,'b'] = np.nan
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [175]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [177]:
# Pass the 0 value to fill up the missing value in df2 while adding to df1
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [178]:
1 /df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [179]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [180]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [183]:
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [184]:
arr = np.arange(12.).reshape((3, 4))

In [185]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [186]:
arr[0] 

array([0., 1., 2., 3.])

In [187]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [205]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon']) 
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [206]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [207]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [210]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [209]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [212]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [213]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [214]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Applicatrion and Mapping 

In [215]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [216]:
frame

b         d         e
Utah   -0.473714 -0.746020  0.594151
Ohio   -1.006752 -0.016219  0.209829
Texas  -0.232441  1.404850 -0.264324
Oregon  1.320336  0.593837 -0.846859

In [217]:
np.abs(frame)

b         d         e
Utah    0.473714  0.746020  0.594151
Ohio    1.006752  0.016219  0.209829
Texas   0.232441  1.404850  0.264324
Oregon  1.320336  0.593837  0.846859

In [218]:
f = lambda x: x.max() - x.min()

In [219]:
frame.apply(f)

b    2.327088
d    2.150871
e    1.441010
dtype: float64

In [220]:
frame.apply(f, axis = 'columns')

Utah      1.340171
Ohio      1.216581
Texas     1.669175
Oregon    2.167195
dtype: float64

In [222]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min','max'])

In [223]:
frame.apply()

b        d         e
min -1.006752 -0.74602 -0.846859
max  1.320336  1.40485  0.594151

In [224]:
format = lambda x: '%.2f' % x

In [225]:
frame.applymap(format)

b      d      e
Utah    -0.47  -0.75   0.59
Ohio    -1.01  -0.02   0.21
Texas   -0.23   1.40  -0.26
Oregon   1.32   0.59  -0.85

In [226]:
frame['e'].map(format)

Utah       0.59
Ohio       0.21
Texas     -0.26
Oregon    -0.85
Name: e, dtype: object

# Sorting and Ranking

In [229]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c']) 
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [230]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c']) 
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [231]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [232]:
frame.sort_index(axis=1, ascending=False) 

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [235]:
obj = pd.Series([4, 7, -3, -2])
obj.sort_values()

2   -3
3   -2
0    4
1    7
dtype: int64

In [236]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [237]:
frame = pd.DataFrame({'b': [4, 7 , -3, 2], 'a':[0,1,0,1]})

In [239]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [240]:
frame.sort_values(by= 'b')


b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [242]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [243]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [244]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [245]:
#  Assign tie values the maximum rank in the group
obj.rank(ascending = False, method= 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [247]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [248]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Aixs Indexes with uplicate Labels

In [249]:
obj = pd.Series(range(5), index = ['a','a','b','b','c'])

In [250]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [251]:
obj.index.is_unique

False

In [252]:
obj['a']

a    0
a    1
dtype: int64

In [253]:
obj['c']

4

In [254]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a', 'a', 'b', 'b'])

In [255]:
df

0         1         2
a -0.045703 -0.193994 -0.970700
a -0.996742 -1.867860 -1.225123
b  3.357548 -0.266761 -0.895279
b  1.759267  1.388135  0.289629

In [256]:
df.loc['b']

0         1         2
b  3.357548 -0.266761 -0.895279
b  1.759267  1.388135  0.289629

## Summarizing and Computing Descriptive Statistics

In [259]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two']) 

In [260]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [261]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [262]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [263]:
df.mean(axis= 'columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [264]:
df.idxmax()

one    b
two    d
dtype: object

In [265]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [266]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [267]:
#  non-numeric data with describe method()
obj = pd.Series(['a','a','b','c'] * 4)

In [268]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [269]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Correaltion and Covariance

In [271]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']} 

In [275]:
price = pd.DataFrame({ticker: data['Adj Close']
                for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                for ticker, data in all_data.items()})

In [278]:
returns = price.pct_change()
price.tail() #Explore the price real data by time series

AAPL         IBM        MSFT         GOOG
Date                                                       
2020-12-24  131.970001  124.690002  222.750000  1738.849976
2020-12-28  136.690002  124.820000  224.960007  1776.089966
2020-12-29  134.869995  123.800003  224.149994  1758.719971
2020-12-30  133.720001  124.339996  221.679993  1739.520020
2020-12-31  132.690002  125.879997  222.419998  1751.880005

In [277]:
returns.tail() # return the data changing on different dates in a percentage way

AAPL       IBM      MSFT      GOOG
Date                                              
2020-12-24  0.007712  0.006376  0.007827  0.003735
2020-12-28  0.035766  0.001043  0.009921  0.021416
2020-12-29 -0.013315 -0.008172 -0.003601 -0.009780
2020-12-30 -0.008527  0.004362 -0.011019 -0.010917
2020-12-31 -0.007703  0.012385  0.003338  0.007105

In [280]:
returns['MSFT'].corr(returns['IBM'])

0.5533609974659119

In [282]:
returns['MSFT'].cov(returns['IBM'])

0.00015741985617450147

In [283]:
returns.MSFT.corr(returns.IBM)

0.5533609974659119

In [284]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.468628  0.713865  0.655150
IBM   0.468628  1.000000  0.553361  0.517245
MSFT  0.713865  0.553361  1.000000  0.777960
GOOG  0.655150  0.517245  0.777960  1.000000

In [285]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000145  0.000237  0.000207
IBM   0.000145  0.000265  0.000157  0.000140
MSFT  0.000237  0.000157  0.000306  0.000226
GOOG  0.000207  0.000140  0.000226  0.000276

In [286]:
returns.corrwith(returns.IBM)

AAPL    0.468628
IBM     1.000000
MSFT    0.553361
GOOG    0.517245
dtype: float64

In [287]:
returns.corrwith(volume)

AAPL   -0.089417
IBM    -0.076793
MSFT   -0.093509
GOOG   -0.163284
dtype: float64

In [288]:
returns.corrwith(volume, axis=1)

Date
2016-01-04         NaN
2016-01-05   -0.956033
2016-01-06   -0.699009
2016-01-07   -0.845447
2016-01-08    0.733068
                ...   
2020-12-24    0.580345
2020-12-28    0.811470
2020-12-29   -0.674348
2020-12-30   -0.255787
2020-12-31   -0.945050
Length: 1259, dtype: float64

In [289]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c']) 

In [290]:
uniques = obj.unique()

In [292]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [302]:
uniques = obj.unique()
print(uniques)

['c' 'a' 'd' 'b']


In [303]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [304]:
pd.value_counts(obj.values, sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [305]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [306]:
mask = obj.isin(['b', 'c'])

In [307]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [308]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [309]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c','b','a'])
pd.Index(unique_vals).get_indexer(to_match)


array([0, 2, 1, 1, 0, 2], dtype=int64)

In [310]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],                   'Qu2': [2, 3, 1, 2, 3],                 'Qu3': [1, 5, 2, 4, 4]}) 

In [311]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [312]:
result = data.apply(pd.value_counts).fillna(0)

In [313]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0